# -*- coding: utf-8 -*-
"""Prog_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oWZYd23INrb1Zfl3CLLRfPNgUtG4Mq48
"""

# 2. Write a Python program that displays your name and age

name = input("Enter your name:: ");
age = int(input("Enter your age:: "));

print("Name:: ", name, "\nAge:: ", age);