# -*- coding: utf-8 -*-
"""Prog_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oWZYd23INrb1Zfl3CLLRfPNgUtG4Mq48
"""

# 3. Write code to print all the pre-defined keywords in Python using the keyword library8

import keyword

print(keyword.kwlist);